### ISSUE TITLE
集成问题

### ISSUE THREAD

**Issue by ncworm** [umdk/UCDLive_Android#21]
我集成了demo中的 LiveCameraView，LiveRoomView  推流地址传进去了
但是 
boolean isSucceed = STREAM_ENV_HOLDER.easyStreamer.prepare(STREAM_ENV_HOLDER.streamingProfile);
还是返回false

**Comment by ncworm** [comment]
![default](https://user-images.githubusercontent.com/10293741/31808581-68790ae2-b5a6-11e7-8942-f5d3fb204307.png)
集成了这3个aar

**Comment by rainccrun** [comment]
谢谢反馈，这边修复了相关代码，麻烦将demo更新至最新
