### ISSUE TITLE
推流问题

### ISSUE THREAD

**Issue by ncworm** [umdk/UCDLive_Android#22]
STREAM_ENV_HOLDER.easyStreamer.prepare(STREAM_ENV_HOLDER.streamingProfile);返回TRUE了。但是控制台内监测不到流量和主播人数变化是什么原因呢，在哪里是能查看是否推流成功呢？

**Comment by michaelchen11** [comment]
推流状态详见 https://github.com/umdk/UCDLive_Android/wiki/5-%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#5.1
具体代码可参考 Demo 中的 LiveCameraView.java

**Comment by ncworm** [comment]
这个状态应该正确的了吧，
![default](https://user-images.githubusercontent.com/10293741/31871570-e15e9b00-b7e7-11e7-8acf-fde322dab1df.png)
推流速度和时长空值正常吗

**Comment by michaelchen11** [comment]
方便的话加下qq 2851147707
