### ISSUE TITLE
直播摄像头旋转

### ISSUE THREAD

**Issue by ccvtgll** [umdk/UCDLive_Android#24]
集成直播时设备摄像头需要旋转，sdk中没找到设置旋转的api,就是UCameraProfile.DirectionMode这个参数不知道怎么设置

**Comment by michaelchen11** [comment]
sdk默认内部处理了摄像头旋转

**Comment by ccvtgll** [comment]
我现在设备上摄像头和手机不太一样，需要旋转，不能外部设置吗？

**Comment by michaelchen11** [comment]
方便的话加下qq 2851147707
