### ISSUE TITLE
安卓8.0的系统有部分不兼容

### ISSUE THREAD

**Issue by sssider** [umdk/UCDLive_Android#26]
在安卓8.x, 第一次进入推流录制的时候，画面会变形，需要重新选择一下分辨率才可以正常。
在安卓7.x和安卓6.x是没这个问题的。
测试过的手机有小米，红米，华为，一加手机等

名称 | 描述
-- | --
设备型号 | 小米6，华为荣耀8，一加6
系统版本 | Android 8.x
SDK 版本 | v2.0.3
问题描述 | 进入推流录制的时候，画面会变形，需要重新选择一下分辨率才可以正常。
操作路径 | 每次进入推流录制

名称 | 描述
-- | --
设备型号 | 小米 note3
系统版本 | Android 7.x
SDK 版本 | v2.0.3
问题描述 | 没问题，一切正常。

名称 | 描述
-- | --
设备型号 | 红米 NOTE3，华为荣耀7
系统版本 | Android 6.x
SDK 版本 | v2.0.3
问题描述 | 没问题，一切正常。

![error_001](https://user-images.githubusercontent.com/38682459/46739011-23c34b80-ccd2-11e8-9092-aa93897aa442.jpg)
![normal_001](https://user-images.githubusercontent.com/38682459/46739013-245be200-ccd2-11e8-9335-204e26253b2a.jpg)

**Comment by tanliwen999** [comment]
@sssider 已做了修改更新，麻烦更新至ulive-android-sdk-2.0.4 ucommon-android-sdk-2.0.2 版本试下。

**Comment by sssider** [comment]
@tanliwen999 谈些，已测试可行。
