### ISSUE TITLE
Sorry no such domain, code = -2, please contact us AE AM.

### ISSUE THREAD

**Issue by pavkoo** [umdk/UCDLive_Android#27]
直播推流报错如题

描述:
UStreamingContext.init(getApplicationContext(), "publish3-key");
我并不开启防盗链,所以使用了publish3-key

我的推流地址为:rtmp://push.mapi.ttdeng.com/live/A110993?record=true&filename=A110993
其中push.mapi.ttdeng.com已经做了dns转发

**Comment by tanliwen999** [comment]
@pavkoo https://github.com/umdk/UCDLive_Android/wiki/8-%E5%8F%8D%E9%A6%88%E5%92%8C%E5%BB%BA%E8%AE%AE#8.1
