### ISSUE TITLE
Android  推流开始的时候 显示  Streaming Signture fail。 这个是什么问题？

### ISSUE THREAD

**Issue by zhijianfree** [umdk/UCDLive_Android#7]
签名问题？  我没有看到哪里有设置的公私钥的地方

**Comment by michaelchen11** [comment]
该提示表示推流鉴权失败，鉴权所需的 accessKey 可能尚未初始化，具体请参考文档: [添加推流鉴权 accessKey](https://github.com/umdk/UCDLive_Android/wiki/4-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#4.2.2)
