### ISSUE TITLE
sdk是否提供调整音频的码率的接口？

### ISSUE THREAD

**Issue by tallboy105** [umdk/UCDLive_Android#8]
app集成推流sdk，
需要较高的音频质量，需要调整音频的码率
sdk提供这个接口吗

**Comment by tanliwen** [comment]
@tallboy105 
 UAudioProfile audioProfile = new UAudioProfile()
                    .bitrate(UAudioProfile.AUDIO_BITRATE_NORMAL) //默认128 可以自己传值进去
                    .channels(UAudioProfile.CHANNEL_IN_STEREO)
                    .source(UAudioProfile.AUDIO_SOURCE_MIC)
                    .format(UAudioProfile.FORMAT_PCM_16BIT)
                    .samplerate(UAudioProfile.SAMPLE_RATE_44100_HZ);
